package com.bzhang.xialiao.mapper;

import com.bzhang.xialiao.pojo.ScChatMsg;
import com.bzhang.xialiao.pojo.ScChatMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScChatMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_chat_msg
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    long countByExample(ScChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_chat_msg
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int deleteByExample(ScChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_chat_msg
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int insert(ScChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_chat_msg
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int insertSelective(ScChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_chat_msg
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    List<ScChatMsg> selectByExample(ScChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_chat_msg
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ScChatMsg record, @Param("example") ScChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_chat_msg
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int updateByExample(@Param("record") ScChatMsg record, @Param("example") ScChatMsgExample example);
}