package com.bzhang.xialiao.mapper;

import com.bzhang.xialiao.pojo.ScFriendsRequest;
import com.bzhang.xialiao.pojo.ScFriendsRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScFriendsRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_friends_request
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    long countByExample(ScFriendsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_friends_request
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int deleteByExample(ScFriendsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_friends_request
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int insert(ScFriendsRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_friends_request
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int insertSelective(ScFriendsRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_friends_request
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    List<ScFriendsRequest> selectByExample(ScFriendsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_friends_request
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ScFriendsRequest record, @Param("example") ScFriendsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_friends_request
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int updateByExample(@Param("record") ScFriendsRequest record, @Param("example") ScFriendsRequestExample example);
}