package com.bzhang.xialiao.mapper;

import com.bzhang.xialiao.pojo.ScMyFriends;
import com.bzhang.xialiao.pojo.ScMyFriendsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScMyFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_my_friends
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    long countByExample(ScMyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_my_friends
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int deleteByExample(ScMyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_my_friends
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int insert(ScMyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_my_friends
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int insertSelective(ScMyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_my_friends
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    List<ScMyFriends> selectByExample(ScMyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_my_friends
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ScMyFriends record, @Param("example") ScMyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_my_friends
     *
     * @mbg.generated Wed May 08 11:27:00 CST 2019
     */
    int updateByExample(@Param("record") ScMyFriends record, @Param("example") ScMyFriendsExample example);
}