package com.bzhang.xialiao.pojo;

import java.util.Date;

public class ScFriendsRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_friends_request.id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_friends_request.send_user_id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String sendUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_friends_request.accept_user_id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String acceptUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_friends_request.is_handle
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private Byte isHandle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_friends_request.request_datetime
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private Date requestDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_friends_request.id
     *
     * @return the value of sc_friends_request.id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_friends_request.id
     *
     * @param id the value for sc_friends_request.id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_friends_request.send_user_id
     *
     * @return the value of sc_friends_request.send_user_id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_friends_request.send_user_id
     *
     * @param sendUserId the value for sc_friends_request.send_user_id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setSendUserId(String sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_friends_request.accept_user_id
     *
     * @return the value of sc_friends_request.accept_user_id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getAcceptUserId() {
        return acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_friends_request.accept_user_id
     *
     * @param acceptUserId the value for sc_friends_request.accept_user_id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setAcceptUserId(String acceptUserId) {
        this.acceptUserId = acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_friends_request.is_handle
     *
     * @return the value of sc_friends_request.is_handle
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public Byte getIsHandle() {
        return isHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_friends_request.is_handle
     *
     * @param isHandle the value for sc_friends_request.is_handle
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setIsHandle(Byte isHandle) {
        this.isHandle = isHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_friends_request.request_datetime
     *
     * @return the value of sc_friends_request.request_datetime
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public Date getRequestDatetime() {
        return requestDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_friends_request.request_datetime
     *
     * @param requestDatetime the value for sc_friends_request.request_datetime
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setRequestDatetime(Date requestDatetime) {
        this.requestDatetime = requestDatetime;
    }
}