package com.bzhang.xialiao.pojo;

import java.util.Date;

public class ScUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.username
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.password
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.face_image
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String faceImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.face_image_big
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String faceImageBig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.nickname
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.phone
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.qrcode
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String qrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.cid
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.created
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_users.updated
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.id
     *
     * @return the value of sc_users.id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.id
     *
     * @param id the value for sc_users.id
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.username
     *
     * @return the value of sc_users.username
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.username
     *
     * @param username the value for sc_users.username
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.password
     *
     * @return the value of sc_users.password
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.password
     *
     * @param password the value for sc_users.password
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.face_image
     *
     * @return the value of sc_users.face_image
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getFaceImage() {
        return faceImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.face_image
     *
     * @param faceImage the value for sc_users.face_image
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setFaceImage(String faceImage) {
        this.faceImage = faceImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.face_image_big
     *
     * @return the value of sc_users.face_image_big
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getFaceImageBig() {
        return faceImageBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.face_image_big
     *
     * @param faceImageBig the value for sc_users.face_image_big
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setFaceImageBig(String faceImageBig) {
        this.faceImageBig = faceImageBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.nickname
     *
     * @return the value of sc_users.nickname
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.nickname
     *
     * @param nickname the value for sc_users.nickname
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.phone
     *
     * @return the value of sc_users.phone
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.phone
     *
     * @param phone the value for sc_users.phone
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.qrcode
     *
     * @return the value of sc_users.qrcode
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.qrcode
     *
     * @param qrcode the value for sc_users.qrcode
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.cid
     *
     * @return the value of sc_users.cid
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.cid
     *
     * @param cid the value for sc_users.cid
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.created
     *
     * @return the value of sc_users.created
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.created
     *
     * @param created the value for sc_users.created
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_users.updated
     *
     * @return the value of sc_users.updated
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_users.updated
     *
     * @param updated the value for sc_users.updated
     *
     * @mbg.generated Tue May 21 11:02:46 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}